module.exports = {
  ADDED_TRACK_REGISTERED: "ADDED_TRACK_REGISTERED",
  PLAYLISTS_RECEIVED: "PLAYLISTS_RECEIVED",
  PLAYLIST_RECEIVED: "PLAYLIST_RECEIVED",
  PLAYLIST_CREATED: "PLAYLIST_CREATED",
  PLAYLIST_DELETED: "PLAYLIST_DELETED",
  PLAYLIST_UPDATED: "PLAYLIST_UPDATED",
  TRACK_ADDED: "TRACK_ADDED"
};
