module.exports = {
  TRACKS_RECEIVED: "TRACKS_RECEIVED",
  SEARCHED_TRACKS_RECEIVED: "SEARCHED_TRACKS_RECEIVED",
  TRACK_CREATED: "TRACK_CREATED",
  TRACK_RECEIVED: "TRACK_RECEIVED",
  CLEAR_SEARCH: "CLEAR_SEARCH",
  NEW_TRACK_PLAYING: "NEW_TRACK_PLAYING"
};
